# Generated by Django 3.0 on 2020-09-07 21:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Acter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=64)),
                ('second_name', models.CharField(max_length=64)),
                ('biography', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='acters')),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preview', models.ImageField(upload_to='movie/preview')),
                ('title', models.CharField(max_length=64)),
                ('description', models.TextField()),
                ('movie', models.FileField(upload_to='movie/', validators=[django.core.validators.FileExtensionValidator(['mp4', 'mov', 'moov', 'mod'])])),
                ('likes', models.PositiveSmallIntegerField(default=0)),
                ('dislikes', models.PositiveSmallIntegerField(default=0)),
                ('acters', models.ManyToManyField(to='app.Acter')),
            ],
        ),
    ]
