# Generated by Django 3.0 on 2020-09-07 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usrauth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='profile',
            field=models.ImageField(blank=True, null=True, upload_to='account/profile'),
        ),
    ]
