make dev:
	python3 manage.py runserver 

make mig:
	python3 manage.py makemigrations 
	python3 manage.py migrate

make susr:
	python3 manage.py createsuperuser

make shell:
	python3 manage.py shell

make venv:
	source ../venv/bin/activate